branch-defaults:
  default:
    environment: blue-env
global:
  application_name: web2048
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
